const fs = require('fs')
const path = require('path')

console.log('Running postinstall script for unbloat...') // Log the start of the script...

const packageJsonPath = path.resolve(process.env.INIT_CWD, 'package.json') // ...use INIT_CWD to define the path to the package.json file...

console.log('Initial working directory (project root):', process.env.INIT_CWD) // ...log the current working directory

console.log('Path to package.json:', packageJsonPath) // ...log the path to package.json...

try {
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8')) // ...and read it...
  console.log('Successfully read package.json') // ...log successful read...

  packageJson.scripts = packageJson.scripts || {} // ...if it doesn't exist, create it...

  packageJson.scripts['unbloat'] = 'node ./node_modules/unbloat/unbloat.js' // ...add the unbloat script...

  console.log('Updated scripts object:', packageJson.scripts) // ...log the updated scripts object...

  fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2), 'utf8') // ...and write the changes back to the package.json file...

  console.log('Successfully updated package.json with unbloat script.') // ...log successful update...

} catch (error) {
  console.error('Error updating package.json:', error) // ...log any errors encountered
}