const fs = require('fs')
const path = require('path')

const packageJsonPath = path.resolve(process.cwd(), 'package.json') //Define the path to the package.json file...

const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8')) //...and read it...

packageJson.scripts = packageJson.scripts || {} //...if it doesn't exist, create it...
packageJson.scripts['unbloat'] = 'node ./node_modules/unbloat/unbloat.js' //...add the unbloat script...

fs.writeFileSync(packageJsonPath, JSON.stringify(packageJson, null, 2), 'utf8') //...and write the changes back to the package.json file